# -*- coding: utf-8 -*-
"""statistics_trends_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Isjd1spxQ_My4EpO1ShZGImy6j9DrIMv

## STATISTICAL ANALYSIS OF LIFE EXPECTANCY AND ECONOMIC INDICATORS

###1. Introduction

This analysis explores the relationship between economic and health indicators using a global dataset. The dataset includes variables such as GDP, life expectancy, and population across different countries.

The objective of this study is to identify trends, relationships, and patterns in the data using statistical techniques and visualizations. The analysis includes data cleaning, computation of statistical moments, and the creation of relational, categorical, and statistical plots to support findings.

###2. Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

"""###2. Load Dataset"""

df = pd.read_csv("Life Expectancy Data.csv")

print(df.head())

"""###3. Clean Column Names"""

df.columns = df.columns.str.strip()
print(df.columns)

"""###4. Handle Missing Values"""

df.fillna(df.mean(numeric_only=True), inplace=True)

"""###5. Verify Cleaning"""

print(df.isnull().sum())

"""###6. Statistical Moments"""

mean = df.mean(numeric_only=True)
print("Mean:\n", df.mean(numeric_only=True))
print("Variance:\n", df.var(numeric_only=True))
print("Skewness:\n", df.skew(numeric_only=True))
print("Kurtosis:\n", df.kurt(numeric_only=True))

"""Mean

- The average life expectancy is around 69 years, indicating overall moderate global health conditions.

- The mean GDP (~5566) shows economic variation across countries.

- The average schooling (~12 years) suggests moderate education levels globally.

Variance

- High variance in GDP and Population indicates large differences between countries.

- Variables like Measles and infant deaths show high variation, indicating inequality in health conditions.

Skewness

- GDP (4.51) and Population (14.18) are highly positively skewed, meaning a few countries have extremely high values.

- Life expectancy (-0.62) is slightly negatively skewed, indicating more countries have higher life expectancy.

- Measles and infant deaths are highly right-skewed, showing extreme values in some countries.

Kurtosis

- Population (230) and GDP (28) have very high kurtosis, indicating extreme outliers.

- Measles and under-five deaths also show high kurtosis, suggesting extreme cases.

- Life expectancy has near-zero kurtosis, indicating a relatively normal distribution.

###7. Relational Plot (Scatter Plot)
"""

sns.scatterplot(data=df, x="GDP", y="Life expectancy")
plt.title("GDP vs Life Expectancy")
plt.xlabel("GDP")
plt.ylabel("Life Expectancy")
plt.show()

"""The scatter plot shows a positive correlation between GDP and life expectancy.
Economic growth is associated with improved health outcomes.

###8. Categorical Plot (Bar Chart)
"""

top10 = df.groupby("Country")["GDP"].mean().sort_values(ascending=False).head(10)

top10.plot(kind="bar", color="skyblue")
plt.title("Top 10 Countries by GDP")
plt.xlabel("Country")
plt.ylabel("GDP")
plt.show()

"""The bar chart shows significant variation in GDP among countries.
This highlights economic inequality.

###9. Statistical Plot (Full Heatmap)
"""

plt.figure(figsize=(12, 8))

corr = df.corr(numeric_only=True)

sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    linewidths=0.5,
    annot_kws={"size":8}
)

plt.title("Correlation Heatmap", fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

"""###10. Focused Correlation Heatmap"""

selected = df[["Life expectancy", "GDP", "Schooling", "Income composition of resources"]]

corr2 = selected.corr()

sns.heatmap(corr2, annot=True, cmap="coolwarm")
plt.title("Key Variable Correlation")
plt.show()

"""Life expectancy shows strong positive correlation with GDP and schooling.
Higher income composition is associated with better health outcomes.
Education and economic development play a key role in improving life expectancy.

###11. Conclusion

This analysis examined the relationship between economic and health indicators across countries. The dataset was cleaned and prepared using appropriate data handling techniques, including mean imputation for missing values.

Statistical analysis revealed significant variation and skewness in key variables such as GDP and population, indicating inequality among countries. Visualizations demonstrated a positive relationship between GDP and life expectancy, suggesting that economic development contributes to better health outcomes.

The correlation analysis further confirmed that education and income composition are strongly associated with improved life expectancy. Overall, the study highlights the importance of economic and social factors in determining global health conditions.
"""